"""Add extraction_sessions table and link to pain_points

Revision ID: 3930f7dae2be
Revises: b1c13a824012
Create Date: 2025-11-24 01:47:24.245520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3930f7dae2be'
down_revision: Union[str, None] = 'b1c13a824012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_name', sa.String(length=255), nullable=True),
    sa.Column('items_processed', sa.Integer(), nullable=True),
    sa.Column('pain_points_extracted', sa.Integer(), nullable=True),
    sa.Column('items_skipped', sa.Integer(), nullable=True),
    sa.Column('avg_opportunity_score', sa.Float(), nullable=True),
    sa.Column('high_severity_count', sa.Integer(), nullable=True),
    sa.Column('critical_severity_count', sa.Integer(), nullable=True),
    sa.Column('category_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_sessions_created_at'), 'extraction_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_extraction_sessions_id'), 'extraction_sessions', ['id'], unique=False)
    op.add_column('pain_points', sa.Column('extraction_session_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_pain_points_extraction_session_id'), 'pain_points', ['extraction_session_id'], unique=False)
    op.create_foreign_key(None, 'pain_points', 'extraction_sessions', ['extraction_session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pain_points', type_='foreignkey')
    op.drop_index(op.f('ix_pain_points_extraction_session_id'), table_name='pain_points')
    op.drop_column('pain_points', 'extraction_session_id')
    op.drop_index(op.f('ix_extraction_sessions_id'), table_name='extraction_sessions')
    op.drop_index(op.f('ix_extraction_sessions_created_at'), table_name='extraction_sessions')
    op.drop_table('extraction_sessions')
    # ### end Alembic commands ###
