"""Initial schema

Revision ID: b1c13a824012
Revises: 
Create Date: 2025-11-23 23:00:22.099668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1c13a824012'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('subreddit', sa.String(length=255), nullable=True),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('scraped_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('is_negative', sa.Boolean(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id')
    )
    op.create_index(op.f('ix_raw_data_created_at'), 'raw_data', ['created_at'], unique=False)
    op.create_index(op.f('ix_raw_data_id'), 'raw_data', ['id'], unique=False)
    op.create_index(op.f('ix_raw_data_is_negative'), 'raw_data', ['is_negative'], unique=False)
    op.create_index(op.f('ix_raw_data_processed'), 'raw_data', ['processed'], unique=False)
    op.create_index(op.f('ix_raw_data_source'), 'raw_data', ['source'], unique=False)
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('subreddits', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_run', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_id'), 'search_queries', ['id'], unique=False)
    op.create_table('pain_points',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_data_id', sa.Integer(), nullable=True),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('mention_count', sa.Integer(), nullable=True),
    sa.Column('first_seen', sa.TIMESTAMP(), nullable=True),
    sa.Column('last_seen', sa.TIMESTAMP(), nullable=True),
    sa.Column('embedding', Vector(dim=1536), nullable=True),
    sa.Column('related_product', sa.String(length=255), nullable=True),
    sa.Column('related_industry', sa.String(length=100), nullable=True),
    sa.Column('target_audience', sa.String(length=100), nullable=True),
    sa.Column('suggested_solution', sa.Text(), nullable=True),
    sa.Column('opportunity_score', sa.Integer(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['raw_data_id'], ['raw_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pain_points_category'), 'pain_points', ['category'], unique=False)
    op.create_index(op.f('ix_pain_points_id'), 'pain_points', ['id'], unique=False)
    op.create_index(op.f('ix_pain_points_opportunity_score'), 'pain_points', ['opportunity_score'], unique=False)
    op.create_index(op.f('ix_pain_points_severity'), 'pain_points', ['severity'], unique=False)
    op.create_table('scrape_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('query_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('items_scraped', sa.Integer(), nullable=True),
    sa.Column('items_negative', sa.Integer(), nullable=True),
    sa.Column('pain_points_extracted', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['query_id'], ['search_queries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scrape_jobs_id'), 'scrape_jobs', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scrape_jobs_id'), table_name='scrape_jobs')
    op.drop_table('scrape_jobs')
    op.drop_index(op.f('ix_pain_points_severity'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_opportunity_score'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_id'), table_name='pain_points')
    op.drop_index(op.f('ix_pain_points_category'), table_name='pain_points')
    op.drop_table('pain_points')
    op.drop_index(op.f('ix_search_queries_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_raw_data_source'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_processed'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_is_negative'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_id'), table_name='raw_data')
    op.drop_index(op.f('ix_raw_data_created_at'), table_name='raw_data')
    op.drop_table('raw_data')
    # ### end Alembic commands ###
